version: '3.8'

services:
  web:
    container_name: trettvik-site
    build:
      context: .
      dockerfile: docker/dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/usr/share/nginx/html
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
